In [14]:
import os



In [9]:
try:
    num = int(input("Enter number: "))
    result = 10 / num
except ValueError:
    print("Not integer")
except ZeroDivisionError:
    print("Cannot divide by zero")
else:
    print(result)
finally:
    print("Execution complete")

0.0008101758081503687
Execution complete


In [17]:
try:
    file = open("example.txt", "r")
    content = file.read()
    print(pow(2,3))
except ImportError:
    print("Module not imported")
except FileNotFoundError:
    print("File does not exist")

finally:
    if 'file' in locals() and not file.closed:
        print(content)
        file.close()
        print("File closed")

8
hello
i 
am 
sanjeev

File closed


In [14]:
class Person:

    def __init__(self, name, age):
        self.__name = name
        self.__age = age
    
    def set_name(self, name):
        if(name == "S%" or name == "s%"): 
            self.__name = name
        else:
            print("Name doesn't start with S")
    def get_name(self):
        return self.__name

    def set_age(self, age):
        if age >= 0:
            self.__age = age
        else:
            print("Age cannot be negative")

    def get_age(self):
        return self.__age
    
p = Person("Sanjeev",21)
print(p.get_age())
print(p.get_name())
q = Person("anjeev",-21)
p.set_age(-21)
p.set_name("anjeev")
print(q.get_age())
print(q.get_name())

    

21
Sanjeev
Age cannot be negative
Name doesn't start with S
-21
anjeev


In [ ]:
class Person:

    def __init__(self, name, age):
        self.__name = name
        self.__age = age

    def get_name(self):
        return self.__name

    def set_age(self, age):
        if age >= 0:
            self.__age = age
        else:
            print("Age cannot be negative")

    def get_age(self):
        return self.__age

In [25]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def __str__(self):
        return f"Person (Name = {self.name}, Age = {self.age} years old)"
p = Person("Krish", 34)
print(p)

Person (Name = Krish, Age = 34 years old)


In [4]:
class Vector:

    def __init__(self, x, y):
        self.x = x
        self.y = y

    # addition
    def __add__(self, other):
        return Vector(self.x + other.x,
                      self.y + other.y)

    # subtraction
    def __sub__(self, other):
        return Vector(self.x - other.x,
                      self.y - other.y)

    # multiplication by scalar
    def __mul__(self, other):
        return Vector(self.x * other.x,
                      self.y * other.y)

    # equality check
    def __eq__(self, other):
        return self.x == other.x and self.y == other.y

    # printable representation
    def __repr__(self):
        return f"Vector({self.x}, {self.y})"
v1 = Vector(2,3)
v2 = Vector(5,4)

In [7]:
print(v1+v2)
print(v1*v2)
print(v1-v2)
print(v1 != v2)

Vector(7, 7)
Vector(10, 12)
Vector(-3, -1)
True


In [27]:
lst = [1,2,3,4,5]
itr = iter(lst)
print(itr)
print(type(itr))
try :
    print(next(itr))
    print(next(itr))
    print(next(itr))
    print(next(itr))
    print(next(itr))
except StopIteration:
    print("No elements")

<class 'list_iterator'>
1
2
3
4
5


In [25]:
text = "Hello"
itr = iter(text)
try:
    print(next(itr))
    print(next(itr))
    print(next(itr))
    print(next(itr))
    print(next(itr))
    print(next(itr))
    print(next(itr))
    print(next(itr))
except Exception as e:
    print(e)
    

H
e
l
l
o



In [30]:
def square(n):
    for i in range(n):
        yield i*i
print(square(10))  
for i in square(10):
    print(i)

<generator object square at 0x000001F3B6A041E0>
0
1
4
9
16
25
36
49
64
81


In [45]:
sq = square(9)



In [47]:
next(sq)

1

In [50]:
def my_gen():
    yield 1
    yield 2
    yield 3

In [62]:
g = my_gen()

In [63]:
print(my_gen())

<generator object my_gen at 0x000001F3B6A36F00>


In [64]:
next(g)

1

In [65]:
def count():
    x = 0
    while True:
        x+=1
        yield x

In [66]:
count()

<generator object count at 0x000001F3B6392740>

In [67]:
c = count()
print(c)

<generator object count at 0x000001F3B63928C0>


In [77]:
g = (i*i for i in range(5))
l = [i*i for i in range(5)]
print(g)
print(l)

<generator object <genexpr> at 0x000001F3B6A04930>
[0, 1, 4, 9, 16]


In [79]:
next(g)

1

In [80]:
def deco(func):
    def wrapper():
        print("before")
        func()
        print("after")
    return wrapper


In [86]:
@deco
def hello():
    print("hello")
hello()

before
hello
after


Numpy

In [87]:
pip install numpy


   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 1.3 MB/s eta 0:00:10
   - -------------------------------------- 0.5/12.3 MB 1.3 MB/s eta 0:00:10
   - -------------------------------------- 0.5/12.3 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.3 MB 730.2 kB/s eta 0:00:16
   -- ------------------------------------- 0.8/12.3 MB 730.2 kB/s eta 0:00:16
   -- ------------------------------------- 0.8/12.3 MB 730.2 kB/s eta 0:00:16
   --- ------------------------------------ 1.0/12.3 MB 559.3 kB/s eta 0:00:21
   --- ------------------------------------ 1.0/12.3 MB 559.3 kB/s eta 0:00:21
   --- ------------------------------------ 1.0/12.3 MB 559.3 kB/s eta 0:00:21
   ---- ----------------------------------- 1.3/12.3 MB 532.8 kB/s eta 0:00:21
   ---

In [89]:
import numpy as np

In [92]:
arr1 = np.array([1,2,3,4,5,6,7,8])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
(8,)


In [98]:
arr2 = arr1.reshape(1,8)
print(arr2)
print(arr2.shape)

[[1 2 3 4 5 6 7 8]]
(1, 8)


In [102]:
arr3 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [106]:
arr4 = np.arange(0,10,3)
print(arr4)

[0 3 6 9]


In [110]:
print(arr3.reshape(5,2))


[[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]


In [112]:
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [113]:
i = np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [114]:
print(arr3)
print(arr3.shape)
print(arr3.dtype)
print(arr3.size)
print(arr3.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
int64
10
2
